using TaskFlow.Common;
using TaskFlow.DTOs;
using TaskFlow.Models;

namespace TaskFlow.Mappers;

/// <summary>Converts between TaskItem entities and their DTOs.</summary>
public static class TaskItemMappers
{
    // Converts incoming CreateTaskItemDto data into a TaskItem entity, assigning ownership (Id is auto-generated by the database)
    public static TaskItem ToTaskItem(this CreateTaskItemDto dto, string userId) => new()
    {
        UserId = userId,
        Title = dto.Title,
        IsCompleted = dto.IsCompleted
    };

    // Converts a database TaskItem entity into TaskItemDto for returning through the API (only safe fields are exposed to the client)
    public static TaskItemDto ToTaskItemDto(this TaskItem taskItem) => new()
    {
        Id = taskItem.Id,
        Title = taskItem.Title,
        IsCompleted = taskItem.IsCompleted
    };

    // Converts a paginated result of TaskItem entities into a paginated result of TaskItemDto for returning through the API
    public static PagedResponse<TaskItemDto> ToPagedDto(this PagedResponse<TaskItem> paged) => new()
    {
        Items = paged.Items.Select(x => x.ToTaskItemDto()).ToList(),
        TotalCount = paged.TotalCount,
        Page = paged.Page,
        PageSize = paged.PageSize,
        TotalPages = paged.TotalPages
    };
}